
import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import org.apache.http.util.ByteArrayBuffer;
import org.apache.http.util.EncodingUtils;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zhangshuting
 */
public class MainForm extends javax.swing.JFrame {
    String driver = "org.apache.derby.jdbc.EmbeddedDriver";
    String database = "jdbc:derby://localhost:1527/test";
    String username = "shuting";
    String password = "0000";
    Connection connection;
    static String stock,dealprice,tablename;
    String stocknum,inprice,amount;
    double sum = 0;
    double sumnet = 0;
    /**
     * Creates new form MainFrame
     */
    public MainForm(String tablename) throws ClassNotFoundException, SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.tablename = tablename;
        jTextArea1.setText(String.format(" %6s\t%s\t%s\t%s\t     %s\n", "股票代號","買進價格","股數(張)","目前行情成交價","賺賠"));
        Class.forName(driver);
        connection = DriverManager.getConnection(database, username, password);
        Statement statement = connection.createStatement();
        ResultSet rs = statement.executeQuery("SELECT * FROM "+tablename);
        while(rs.next()){
            stocknum = rs.getString("stockno");
            inprice = rs.getString("price");
            amount = rs.getString("amount");
            String result = null;
            String stringURL=("https://tw.stock.yahoo.com/q/q?s="+stocknum);
            try{
                URL myUrl = new URL(stringURL);
                InputStream in = myUrl.openConnection().getInputStream();
                BufferedInputStream bis = new BufferedInputStream(in);
                ByteArrayBuffer baf = new ByteArrayBuffer(bis.available());
                int data = 0;
                while ((data = bis.read()) != -1) {
                    baf.append((byte) data);
                }
                result = EncodingUtils.getString(baf.toByteArray(),"BIG5");
            }catch(IOException e){
            }
            Parser(result);
            Double net = (Double.parseDouble(dealprice)-Double.parseDouble(inprice))*Double.parseDouble(amount);
            jTextArea1.append(String.format("  %6s\t%s\t%s\t%s\t   %.0f\n", stock,inprice,amount,dealprice,net*1000));
            sum+=Double.parseDouble(dealprice)*Double.parseDouble(amount)*1000;
            sumnet+= net*1000;
        }
        connection.close();
        jTextFieldTotal.setText(String.format("%.0f",sum));
        jTextFieldNet.setText(String.format("%.0f",sumnet));         
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jTextFieldStock = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jButtonCreate = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonSold = new javax.swing.JButton();
        jTextFieldAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jTextFieldNet = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonRefresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Gurmukhi MN", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(55, 68, 103));
        jLabel2.setText("買進價格");

        jLabel3.setFont(new java.awt.Font("Gurmukhi MN", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(55, 68, 103));
        jLabel3.setText("股票代號");

        jLabel4.setFont(new java.awt.Font("Gurmukhi MN", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(55, 68, 103));
        jLabel4.setText("股數(張)");

        jSeparator1.setBackground(new java.awt.Color(57, 80, 112));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 50));
        jSeparator1.setSize(new java.awt.Dimension(50, 30));

        jSeparator3.setBackground(new java.awt.Color(57, 80, 112));
        jSeparator3.setPreferredSize(new java.awt.Dimension(50, 50));
        jSeparator3.setSize(new java.awt.Dimension(50, 30));

        jSeparator4.setBackground(new java.awt.Color(57, 80, 112));
        jSeparator4.setPreferredSize(new java.awt.Dimension(50, 50));
        jSeparator4.setSize(new java.awt.Dimension(50, 30));

        jTextFieldStock.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldStock.setFont(new java.awt.Font("Gurmukhi MN", 0, 18)); // NOI18N
        jTextFieldStock.setForeground(new java.awt.Color(0, 51, 102));
        jTextFieldStock.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldStock.setBorder(null);

        jTextFieldPrice.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldPrice.setFont(new java.awt.Font("Gurmukhi MN", 0, 18)); // NOI18N
        jTextFieldPrice.setForeground(new java.awt.Color(0, 51, 102));
        jTextFieldPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPrice.setBorder(null);

        jButtonCreate.setBackground(new java.awt.Color(40, 63, 88));
        jButtonCreate.setFont(new java.awt.Font("Gurmukhi MN", 1, 24)); // NOI18N
        jButtonCreate.setForeground(new java.awt.Color(204, 204, 204));
        jButtonCreate.setText("新增");
        jButtonCreate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCreateMouseClicked(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(40, 63, 88));
        jButtonCancel.setFont(new java.awt.Font("Gurmukhi MN", 1, 24)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(204, 204, 204));
        jButtonCancel.setText("取消");
        jButtonCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelMouseClicked(evt);
            }
        });

        jButtonSold.setBackground(new java.awt.Color(40, 63, 88));
        jButtonSold.setFont(new java.awt.Font("Gurmukhi MN", 1, 24)); // NOI18N
        jButtonSold.setForeground(new java.awt.Color(204, 204, 204));
        jButtonSold.setText("已賣出");
        jButtonSold.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSold.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSoldMouseClicked(evt);
            }
        });

        jTextFieldAmount.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldAmount.setFont(new java.awt.Font("Gurmukhi MN", 0, 18)); // NOI18N
        jTextFieldAmount.setForeground(new java.awt.Color(0, 51, 102));
        jTextFieldAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldAmount.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Gurmukhi MN", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(157, 52, 48));
        jLabel5.setText("總股票估計價格：");

        jTextFieldTotal.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTotal.setFont(new java.awt.Font("Gurmukhi MN", 0, 18)); // NOI18N
        jTextFieldTotal.setForeground(new java.awt.Color(0, 51, 102));
        jTextFieldTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTotal.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Gurmukhi MN", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(157, 52, 48));
        jLabel6.setText("總賺賠：");

        jSeparator5.setBackground(new java.awt.Color(157, 52, 48));
        jSeparator5.setPreferredSize(new java.awt.Dimension(50, 50));
        jSeparator5.setSize(new java.awt.Dimension(50, 30));

        jTextFieldNet.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNet.setFont(new java.awt.Font("Gurmukhi MN", 0, 18)); // NOI18N
        jTextFieldNet.setForeground(new java.awt.Color(0, 51, 102));
        jTextFieldNet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNet.setBorder(null);

        jSeparator6.setBackground(new java.awt.Color(157, 52, 48));
        jSeparator6.setPreferredSize(new java.awt.Dimension(50, 50));
        jSeparator6.setSize(new java.awt.Dimension(50, 30));

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jScrollPane2.setBackground(new java.awt.Color(39, 76, 95));
        jScrollPane2.setForeground(new java.awt.Color(204, 204, 204));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Gurmukhi MN", 0, 20)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 51, 102));
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );

        jButtonRefresh.setBackground(new java.awt.Color(109, 29, 41));
        jButtonRefresh.setFont(new java.awt.Font("Gurmukhi MN", 1, 14)); // NOI18N
        jButtonRefresh.setText("REFRESH");
        jButtonRefresh.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRefreshMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldStock))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldPrice)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                            .addComponent(jTextFieldAmount))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSold, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addGap(3, 3, 3)
                                .addComponent(jTextFieldNet, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSold, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNet)
                    .addComponent(jButtonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Gurmukhi MN", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STOCK");

        jLabelClose.setBackground(new java.awt.Color(255, 255, 255));
        jLabelClose.setFont(new java.awt.Font("Gurmukhi MN", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMin.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMin.setFont(new java.awt.Font("Gurmukhi MN", 1, 36)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 682, Short.MAX_VALUE)
                .addComponent(jLabelMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelClose)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClose)
                    .addComponent(jLabelMin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelMouseClicked
        jTextFieldStock.setText("");
        jTextFieldPrice.setText("");
        jTextFieldAmount.setText("");
    }//GEN-LAST:event_jButtonCancelMouseClicked

    private void jButtonCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateMouseClicked
        if(jTextFieldStock.getText().length() == 0||jTextFieldPrice.getText().length() == 0||jTextFieldAmount.getText().length() == 0){
            JOptionPane.showMessageDialog(null,"Please fill up the empty fields!");
        }else{
            PreparedStatement ps;
            try {
                Class.forName(driver);
                connection = DriverManager.getConnection(database, username, password);
                ps = connection.prepareStatement("INSERT INTO "+tablename+" VALUES (?, ?, ?)");
                ps.setString(1, jTextFieldStock.getText());
                ps.setString(2, jTextFieldPrice.getText());
                ps.setString(3,jTextFieldAmount.getText());
                ps.execute();
                connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        /*String result = null;
        String stringURL=("https://tw.stock.yahoo.com/q/q?s="+jTextFieldStock.getText());
        try{
            URL myUrl = new URL(stringURL);
            InputStream in = myUrl.openConnection().getInputStream();
            BufferedInputStream bis = new BufferedInputStream(in);
            ByteArrayBuffer baf = new ByteArrayBuffer(bis.available());
            int data = 0;
            while ((data = bis.read()) != -1) {
                baf.append((byte) data);
            }
            result = EncodingUtils.getString(baf.toByteArray(),"BIG5");
        }catch(IOException e){
        }
        Parser(result);
        Double net = (Double.parseDouble(dealprice)-Double.parseDouble(jTextFieldPrice.getText()))*Double.parseDouble(jTextFieldAmount.getText());
        jTextArea1.append(String.format("  %6s\t%s\t%s\t%s\t   %.0f\n", stock,jTextFieldPrice.getText(),jTextFieldAmount.getText(),dealprice,net*1000));
        sum+=Double.parseDouble(dealprice)*Double.parseDouble(amount)*1000;
        sumnet+= net*1000;   
        jTextFieldTotal.setText(String.format("%.0f",sum));
        jTextFieldNet.setText(String.format("%.0f",sumnet));*/ 
        jTextFieldStock.setText("");
        jTextFieldPrice.setText("");
        jTextFieldAmount.setText("");
    }//GEN-LAST:event_jButtonCreateMouseClicked

    private void jButtonSoldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSoldMouseClicked
        if(jTextFieldStock.getText().length() == 0&&jTextFieldAmount.getText().length() == 0){
            JOptionPane.showMessageDialog(null,"Please fill up the empty field!");
        }else{
            PreparedStatement ps = null;
            try {
                Class.forName(driver);
                connection = DriverManager.getConnection(database, username, password);
                Statement statement = connection.createStatement();
                ResultSet rs = statement.executeQuery("SELECT * FROM "+tablename);
                while(rs.next()){
                    stocknum = rs.getString("stockno");
                    amount = rs.getString("amount");
                }
                //if(stocknum.equals(jTextFieldStock.getText())&&amount.equals(jTextFieldAmount.getText())){
                ps = connection.prepareStatement("DELETE FROM "+tablename+" WHERE stockno = '"+jTextFieldStock.getText()+"'");
                /*}else{
                    double updateamount = Double.parseDouble(amount)-Double.parseDouble(jTextFieldAmount.getText());
                    ps = connection.prepareStatement("UPDATE "+tablename+" SET amount = "+String.valueOf(updateamount)+" WHERE stockno = "+stocknum);
                }*/
                ps.execute();
                connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jTextFieldStock.setText("");
        jTextFieldPrice.setText("");
        jTextFieldAmount.setText("");
    }//GEN-LAST:event_jButtonSoldMouseClicked

    private void jButtonRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRefreshMouseClicked
        jTextArea1.setText(String.format(" %6s\t%s\t%s\t%s\t     %s\n", "股票代號","買進價格","股數(張)","目前行情成交價","賺賠"));
        try {
            Class.forName(driver);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            connection = DriverManager.getConnection(database, username, password);
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        Statement statement = null;
        try {
            statement = connection.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        ResultSet rs = null;
        try {
            rs = statement.executeQuery("SELECT * FROM "+tablename);
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            sum=0;
            sumnet=0;
            while(rs.next()){
                stocknum = rs.getString("stockno");
                inprice = rs.getString("price");
                amount = rs.getString("amount");
                String result = null;
                String stringURL=("https://tw.stock.yahoo.com/q/q?s="+stocknum);
                try{
                    URL myUrl = new URL(stringURL);
                    InputStream in = myUrl.openConnection().getInputStream();
                    BufferedInputStream bis = new BufferedInputStream(in);
                    ByteArrayBuffer baf = new ByteArrayBuffer(bis.available());
                    int data = 0;
                    while ((data = bis.read()) != -1) {
                        baf.append((byte) data);
                    }
                    result = EncodingUtils.getString(baf.toByteArray(),"BIG5");
                }catch(IOException e){
                }
                Parser(result);
                Double net = (Double.parseDouble(dealprice)-Double.parseDouble(inprice))*Double.parseDouble(amount);
                jTextArea1.append(String.format("  %6s\t%s\t%s\t%s\t   %.0f\n", stock,inprice,amount,dealprice,net*1000));
                sum+=Double.parseDouble(dealprice)*Double.parseDouble(amount)*1000;
                sumnet+= net*1000;
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextFieldTotal.setText(String.format("%.0f",sum));
        jTextFieldNet.setText(String.format("%.0f",sumnet));
    }//GEN-LAST:event_jButtonRefreshMouseClicked

    public static void Parser(String result){
        int start=0,end=0;
            start = result.indexOf("<a href=\"/q/bc?s=1101\">",end+1);
            end = result.indexOf("</a><br>",start+1);
            stock = result.substring(end-6,end);
    
            start = result.indexOf("<td align=\"center\" bgcolor=\"#FFFfff\" nowrap><b>",end+1);
            end = result.indexOf("</b></td>",start+1);
            dealprice = result.substring(start+47,end);
            
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainForm(tablename).setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSold;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldNet;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldStock;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
